/*
OpenSearch

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-11-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opensearch

import (
	"encoding/json"
)

// checks if the DeletePitBodyParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeletePitBodyParams{}

// DeletePitBodyParams struct for DeletePitBodyParams
type DeletePitBodyParams struct {
	PitId []string `json:"pit_id"`
}

// NewDeletePitBodyParams instantiates a new DeletePitBodyParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletePitBodyParams(pitId []string) *DeletePitBodyParams {
	this := DeletePitBodyParams{}
	this.PitId = pitId
	return &this
}

// NewDeletePitBodyParamsWithDefaults instantiates a new DeletePitBodyParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletePitBodyParamsWithDefaults() *DeletePitBodyParams {
	this := DeletePitBodyParams{}
	return &this
}

// GetPitId returns the PitId field value
func (o *DeletePitBodyParams) GetPitId() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.PitId
}

// GetPitIdOk returns a tuple with the PitId field value
// and a boolean to check if the value has been set.
func (o *DeletePitBodyParams) GetPitIdOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PitId, true
}

// SetPitId sets field value
func (o *DeletePitBodyParams) SetPitId(v []string) {
	o.PitId = v
}

func (o DeletePitBodyParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletePitBodyParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pit_id"] = o.PitId
	return toSerialize, nil
}

type NullableDeletePitBodyParams struct {
	value *DeletePitBodyParams
	isSet bool
}

func (v NullableDeletePitBodyParams) Get() *DeletePitBodyParams {
	return v.value
}

func (v *NullableDeletePitBodyParams) Set(val *DeletePitBodyParams) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletePitBodyParams) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletePitBodyParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletePitBodyParams(val *DeletePitBodyParams) *NullableDeletePitBodyParams {
	return &NullableDeletePitBodyParams{value: val, isSet: true}
}

func (v NullableDeletePitBodyParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletePitBodyParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


