/*
OpenSearch

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-11-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RemoteStoreRestoreShardsInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoteStoreRestoreShardsInfo{}

// RemoteStoreRestoreShardsInfo struct for RemoteStoreRestoreShardsInfo
type RemoteStoreRestoreShardsInfo struct {
	Total *int32 `json:"total,omitempty"`
	Failed *int32 `json:"failed,omitempty"`
	Successful *int32 `json:"successful,omitempty"`
}

// NewRemoteStoreRestoreShardsInfo instantiates a new RemoteStoreRestoreShardsInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoteStoreRestoreShardsInfo() *RemoteStoreRestoreShardsInfo {
	this := RemoteStoreRestoreShardsInfo{}
	return &this
}

// NewRemoteStoreRestoreShardsInfoWithDefaults instantiates a new RemoteStoreRestoreShardsInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoteStoreRestoreShardsInfoWithDefaults() *RemoteStoreRestoreShardsInfo {
	this := RemoteStoreRestoreShardsInfo{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *RemoteStoreRestoreShardsInfo) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoteStoreRestoreShardsInfo) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *RemoteStoreRestoreShardsInfo) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *RemoteStoreRestoreShardsInfo) SetTotal(v int32) {
	o.Total = &v
}

// GetFailed returns the Failed field value if set, zero value otherwise.
func (o *RemoteStoreRestoreShardsInfo) GetFailed() int32 {
	if o == nil || IsNil(o.Failed) {
		var ret int32
		return ret
	}
	return *o.Failed
}

// GetFailedOk returns a tuple with the Failed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoteStoreRestoreShardsInfo) GetFailedOk() (*int32, bool) {
	if o == nil || IsNil(o.Failed) {
		return nil, false
	}
	return o.Failed, true
}

// HasFailed returns a boolean if a field has been set.
func (o *RemoteStoreRestoreShardsInfo) HasFailed() bool {
	if o != nil && !IsNil(o.Failed) {
		return true
	}

	return false
}

// SetFailed gets a reference to the given int32 and assigns it to the Failed field.
func (o *RemoteStoreRestoreShardsInfo) SetFailed(v int32) {
	o.Failed = &v
}

// GetSuccessful returns the Successful field value if set, zero value otherwise.
func (o *RemoteStoreRestoreShardsInfo) GetSuccessful() int32 {
	if o == nil || IsNil(o.Successful) {
		var ret int32
		return ret
	}
	return *o.Successful
}

// GetSuccessfulOk returns a tuple with the Successful field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoteStoreRestoreShardsInfo) GetSuccessfulOk() (*int32, bool) {
	if o == nil || IsNil(o.Successful) {
		return nil, false
	}
	return o.Successful, true
}

// HasSuccessful returns a boolean if a field has been set.
func (o *RemoteStoreRestoreShardsInfo) HasSuccessful() bool {
	if o != nil && !IsNil(o.Successful) {
		return true
	}

	return false
}

// SetSuccessful gets a reference to the given int32 and assigns it to the Successful field.
func (o *RemoteStoreRestoreShardsInfo) SetSuccessful(v int32) {
	o.Successful = &v
}

func (o RemoteStoreRestoreShardsInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoteStoreRestoreShardsInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Failed) {
		toSerialize["failed"] = o.Failed
	}
	if !IsNil(o.Successful) {
		toSerialize["successful"] = o.Successful
	}
	return toSerialize, nil
}

type NullableRemoteStoreRestoreShardsInfo struct {
	value *RemoteStoreRestoreShardsInfo
	isSet bool
}

func (v NullableRemoteStoreRestoreShardsInfo) Get() *RemoteStoreRestoreShardsInfo {
	return v.value
}

func (v *NullableRemoteStoreRestoreShardsInfo) Set(val *RemoteStoreRestoreShardsInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoteStoreRestoreShardsInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoteStoreRestoreShardsInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoteStoreRestoreShardsInfo(val *RemoteStoreRestoreShardsInfo) *NullableRemoteStoreRestoreShardsInfo {
	return &NullableRemoteStoreRestoreShardsInfo{value: val, isSet: true}
}

func (v NullableRemoteStoreRestoreShardsInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoteStoreRestoreShardsInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


