/*
OpenSearch

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-11-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ClusterGetSettingsResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterGetSettingsResponseContent{}

// ClusterGetSettingsResponseContent struct for ClusterGetSettingsResponseContent
type ClusterGetSettingsResponseContent struct {
	Persistent map[string]interface{} `json:"persistent,omitempty"`
	Transient map[string]interface{} `json:"transient,omitempty"`
	Defaults map[string]interface{} `json:"defaults,omitempty"`
}

// NewClusterGetSettingsResponseContent instantiates a new ClusterGetSettingsResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterGetSettingsResponseContent() *ClusterGetSettingsResponseContent {
	this := ClusterGetSettingsResponseContent{}
	return &this
}

// NewClusterGetSettingsResponseContentWithDefaults instantiates a new ClusterGetSettingsResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterGetSettingsResponseContentWithDefaults() *ClusterGetSettingsResponseContent {
	this := ClusterGetSettingsResponseContent{}
	return &this
}

// GetPersistent returns the Persistent field value if set, zero value otherwise.
func (o *ClusterGetSettingsResponseContent) GetPersistent() map[string]interface{} {
	if o == nil || IsNil(o.Persistent) {
		var ret map[string]interface{}
		return ret
	}
	return o.Persistent
}

// GetPersistentOk returns a tuple with the Persistent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterGetSettingsResponseContent) GetPersistentOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Persistent) {
		return map[string]interface{}{}, false
	}
	return o.Persistent, true
}

// HasPersistent returns a boolean if a field has been set.
func (o *ClusterGetSettingsResponseContent) HasPersistent() bool {
	if o != nil && !IsNil(o.Persistent) {
		return true
	}

	return false
}

// SetPersistent gets a reference to the given map[string]interface{} and assigns it to the Persistent field.
func (o *ClusterGetSettingsResponseContent) SetPersistent(v map[string]interface{}) {
	o.Persistent = v
}

// GetTransient returns the Transient field value if set, zero value otherwise.
func (o *ClusterGetSettingsResponseContent) GetTransient() map[string]interface{} {
	if o == nil || IsNil(o.Transient) {
		var ret map[string]interface{}
		return ret
	}
	return o.Transient
}

// GetTransientOk returns a tuple with the Transient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterGetSettingsResponseContent) GetTransientOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Transient) {
		return map[string]interface{}{}, false
	}
	return o.Transient, true
}

// HasTransient returns a boolean if a field has been set.
func (o *ClusterGetSettingsResponseContent) HasTransient() bool {
	if o != nil && !IsNil(o.Transient) {
		return true
	}

	return false
}

// SetTransient gets a reference to the given map[string]interface{} and assigns it to the Transient field.
func (o *ClusterGetSettingsResponseContent) SetTransient(v map[string]interface{}) {
	o.Transient = v
}

// GetDefaults returns the Defaults field value if set, zero value otherwise.
func (o *ClusterGetSettingsResponseContent) GetDefaults() map[string]interface{} {
	if o == nil || IsNil(o.Defaults) {
		var ret map[string]interface{}
		return ret
	}
	return o.Defaults
}

// GetDefaultsOk returns a tuple with the Defaults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterGetSettingsResponseContent) GetDefaultsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Defaults) {
		return map[string]interface{}{}, false
	}
	return o.Defaults, true
}

// HasDefaults returns a boolean if a field has been set.
func (o *ClusterGetSettingsResponseContent) HasDefaults() bool {
	if o != nil && !IsNil(o.Defaults) {
		return true
	}

	return false
}

// SetDefaults gets a reference to the given map[string]interface{} and assigns it to the Defaults field.
func (o *ClusterGetSettingsResponseContent) SetDefaults(v map[string]interface{}) {
	o.Defaults = v
}

func (o ClusterGetSettingsResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterGetSettingsResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Persistent) {
		toSerialize["persistent"] = o.Persistent
	}
	if !IsNil(o.Transient) {
		toSerialize["transient"] = o.Transient
	}
	if !IsNil(o.Defaults) {
		toSerialize["defaults"] = o.Defaults
	}
	return toSerialize, nil
}

type NullableClusterGetSettingsResponseContent struct {
	value *ClusterGetSettingsResponseContent
	isSet bool
}

func (v NullableClusterGetSettingsResponseContent) Get() *ClusterGetSettingsResponseContent {
	return v.value
}

func (v *NullableClusterGetSettingsResponseContent) Set(val *ClusterGetSettingsResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterGetSettingsResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterGetSettingsResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterGetSettingsResponseContent(val *ClusterGetSettingsResponseContent) *NullableClusterGetSettingsResponseContent {
	return &NullableClusterGetSettingsResponseContent{value: val, isSet: true}
}

func (v NullableClusterGetSettingsResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterGetSettingsResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


