/*
OpenSearch

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-11-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PatchDistinguishedNamesResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchDistinguishedNamesResponseContent{}

// PatchDistinguishedNamesResponseContent struct for PatchDistinguishedNamesResponseContent
type PatchDistinguishedNamesResponseContent struct {
	// Security Operation Status
	Status *string `json:"status,omitempty"`
	// Security Operation Message
	Message *string `json:"message,omitempty"`
}

// NewPatchDistinguishedNamesResponseContent instantiates a new PatchDistinguishedNamesResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchDistinguishedNamesResponseContent() *PatchDistinguishedNamesResponseContent {
	this := PatchDistinguishedNamesResponseContent{}
	return &this
}

// NewPatchDistinguishedNamesResponseContentWithDefaults instantiates a new PatchDistinguishedNamesResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchDistinguishedNamesResponseContentWithDefaults() *PatchDistinguishedNamesResponseContent {
	this := PatchDistinguishedNamesResponseContent{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PatchDistinguishedNamesResponseContent) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchDistinguishedNamesResponseContent) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PatchDistinguishedNamesResponseContent) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PatchDistinguishedNamesResponseContent) SetStatus(v string) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *PatchDistinguishedNamesResponseContent) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchDistinguishedNamesResponseContent) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *PatchDistinguishedNamesResponseContent) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *PatchDistinguishedNamesResponseContent) SetMessage(v string) {
	o.Message = &v
}

func (o PatchDistinguishedNamesResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchDistinguishedNamesResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullablePatchDistinguishedNamesResponseContent struct {
	value *PatchDistinguishedNamesResponseContent
	isSet bool
}

func (v NullablePatchDistinguishedNamesResponseContent) Get() *PatchDistinguishedNamesResponseContent {
	return v.value
}

func (v *NullablePatchDistinguishedNamesResponseContent) Set(val *PatchDistinguishedNamesResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchDistinguishedNamesResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchDistinguishedNamesResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchDistinguishedNamesResponseContent(val *PatchDistinguishedNamesResponseContent) *NullablePatchDistinguishedNamesResponseContent {
	return &NullablePatchDistinguishedNamesResponseContent{value: val, isSet: true}
}

func (v NullablePatchDistinguishedNamesResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchDistinguishedNamesResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


