/*
OpenSearch

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-11-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IndicesUpdateAliasesBodyParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndicesUpdateAliasesBodyParams{}

// IndicesUpdateAliasesBodyParams The definition of `actions` to perform
type IndicesUpdateAliasesBodyParams struct {
	Actions *ActionObjectStructure `json:"actions,omitempty"`
}

// NewIndicesUpdateAliasesBodyParams instantiates a new IndicesUpdateAliasesBodyParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndicesUpdateAliasesBodyParams() *IndicesUpdateAliasesBodyParams {
	this := IndicesUpdateAliasesBodyParams{}
	return &this
}

// NewIndicesUpdateAliasesBodyParamsWithDefaults instantiates a new IndicesUpdateAliasesBodyParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndicesUpdateAliasesBodyParamsWithDefaults() *IndicesUpdateAliasesBodyParams {
	this := IndicesUpdateAliasesBodyParams{}
	return &this
}

// GetActions returns the Actions field value if set, zero value otherwise.
func (o *IndicesUpdateAliasesBodyParams) GetActions() ActionObjectStructure {
	if o == nil || IsNil(o.Actions) {
		var ret ActionObjectStructure
		return ret
	}
	return *o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndicesUpdateAliasesBodyParams) GetActionsOk() (*ActionObjectStructure, bool) {
	if o == nil || IsNil(o.Actions) {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *IndicesUpdateAliasesBodyParams) HasActions() bool {
	if o != nil && !IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given ActionObjectStructure and assigns it to the Actions field.
func (o *IndicesUpdateAliasesBodyParams) SetActions(v ActionObjectStructure) {
	o.Actions = &v
}

func (o IndicesUpdateAliasesBodyParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndicesUpdateAliasesBodyParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Actions) {
		toSerialize["actions"] = o.Actions
	}
	return toSerialize, nil
}

type NullableIndicesUpdateAliasesBodyParams struct {
	value *IndicesUpdateAliasesBodyParams
	isSet bool
}

func (v NullableIndicesUpdateAliasesBodyParams) Get() *IndicesUpdateAliasesBodyParams {
	return v.value
}

func (v *NullableIndicesUpdateAliasesBodyParams) Set(val *IndicesUpdateAliasesBodyParams) {
	v.value = val
	v.isSet = true
}

func (v NullableIndicesUpdateAliasesBodyParams) IsSet() bool {
	return v.isSet
}

func (v *NullableIndicesUpdateAliasesBodyParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndicesUpdateAliasesBodyParams(val *IndicesUpdateAliasesBodyParams) *NullableIndicesUpdateAliasesBodyParams {
	return &NullableIndicesUpdateAliasesBodyParams{value: val, isSet: true}
}

func (v NullableIndicesUpdateAliasesBodyParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndicesUpdateAliasesBodyParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


