/*
OpenSearch

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-11-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opensearch

import (
	"encoding/json"
)

// checks if the DeleteActionGroupResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteActionGroupResponseContent{}

// DeleteActionGroupResponseContent struct for DeleteActionGroupResponseContent
type DeleteActionGroupResponseContent struct {
	// Security Operation Status
	Status *string `json:"status,omitempty"`
	// Security Operation Message
	Message *string `json:"message,omitempty"`
}

// NewDeleteActionGroupResponseContent instantiates a new DeleteActionGroupResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteActionGroupResponseContent() *DeleteActionGroupResponseContent {
	this := DeleteActionGroupResponseContent{}
	return &this
}

// NewDeleteActionGroupResponseContentWithDefaults instantiates a new DeleteActionGroupResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteActionGroupResponseContentWithDefaults() *DeleteActionGroupResponseContent {
	this := DeleteActionGroupResponseContent{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DeleteActionGroupResponseContent) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteActionGroupResponseContent) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DeleteActionGroupResponseContent) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DeleteActionGroupResponseContent) SetStatus(v string) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DeleteActionGroupResponseContent) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteActionGroupResponseContent) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DeleteActionGroupResponseContent) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DeleteActionGroupResponseContent) SetMessage(v string) {
	o.Message = &v
}

func (o DeleteActionGroupResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteActionGroupResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableDeleteActionGroupResponseContent struct {
	value *DeleteActionGroupResponseContent
	isSet bool
}

func (v NullableDeleteActionGroupResponseContent) Get() *DeleteActionGroupResponseContent {
	return v.value
}

func (v *NullableDeleteActionGroupResponseContent) Set(val *DeleteActionGroupResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteActionGroupResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteActionGroupResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteActionGroupResponseContent(val *DeleteActionGroupResponseContent) *NullableDeleteActionGroupResponseContent {
	return &NullableDeleteActionGroupResponseContent{value: val, isSet: true}
}

func (v NullableDeleteActionGroupResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteActionGroupResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


