/*
OpenSearch

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-11-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RemoteStoreRestoreResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoteStoreRestoreResponseContent{}

// RemoteStoreRestoreResponseContent struct for RemoteStoreRestoreResponseContent
type RemoteStoreRestoreResponseContent struct {
	Accepted *bool `json:"accepted,omitempty"`
	RemoteStore *RemoteStoreRestoreInfo `json:"remote_store,omitempty"`
}

// NewRemoteStoreRestoreResponseContent instantiates a new RemoteStoreRestoreResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoteStoreRestoreResponseContent() *RemoteStoreRestoreResponseContent {
	this := RemoteStoreRestoreResponseContent{}
	return &this
}

// NewRemoteStoreRestoreResponseContentWithDefaults instantiates a new RemoteStoreRestoreResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoteStoreRestoreResponseContentWithDefaults() *RemoteStoreRestoreResponseContent {
	this := RemoteStoreRestoreResponseContent{}
	return &this
}

// GetAccepted returns the Accepted field value if set, zero value otherwise.
func (o *RemoteStoreRestoreResponseContent) GetAccepted() bool {
	if o == nil || IsNil(o.Accepted) {
		var ret bool
		return ret
	}
	return *o.Accepted
}

// GetAcceptedOk returns a tuple with the Accepted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoteStoreRestoreResponseContent) GetAcceptedOk() (*bool, bool) {
	if o == nil || IsNil(o.Accepted) {
		return nil, false
	}
	return o.Accepted, true
}

// HasAccepted returns a boolean if a field has been set.
func (o *RemoteStoreRestoreResponseContent) HasAccepted() bool {
	if o != nil && !IsNil(o.Accepted) {
		return true
	}

	return false
}

// SetAccepted gets a reference to the given bool and assigns it to the Accepted field.
func (o *RemoteStoreRestoreResponseContent) SetAccepted(v bool) {
	o.Accepted = &v
}

// GetRemoteStore returns the RemoteStore field value if set, zero value otherwise.
func (o *RemoteStoreRestoreResponseContent) GetRemoteStore() RemoteStoreRestoreInfo {
	if o == nil || IsNil(o.RemoteStore) {
		var ret RemoteStoreRestoreInfo
		return ret
	}
	return *o.RemoteStore
}

// GetRemoteStoreOk returns a tuple with the RemoteStore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoteStoreRestoreResponseContent) GetRemoteStoreOk() (*RemoteStoreRestoreInfo, bool) {
	if o == nil || IsNil(o.RemoteStore) {
		return nil, false
	}
	return o.RemoteStore, true
}

// HasRemoteStore returns a boolean if a field has been set.
func (o *RemoteStoreRestoreResponseContent) HasRemoteStore() bool {
	if o != nil && !IsNil(o.RemoteStore) {
		return true
	}

	return false
}

// SetRemoteStore gets a reference to the given RemoteStoreRestoreInfo and assigns it to the RemoteStore field.
func (o *RemoteStoreRestoreResponseContent) SetRemoteStore(v RemoteStoreRestoreInfo) {
	o.RemoteStore = &v
}

func (o RemoteStoreRestoreResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoteStoreRestoreResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Accepted) {
		toSerialize["accepted"] = o.Accepted
	}
	if !IsNil(o.RemoteStore) {
		toSerialize["remote_store"] = o.RemoteStore
	}
	return toSerialize, nil
}

type NullableRemoteStoreRestoreResponseContent struct {
	value *RemoteStoreRestoreResponseContent
	isSet bool
}

func (v NullableRemoteStoreRestoreResponseContent) Get() *RemoteStoreRestoreResponseContent {
	return v.value
}

func (v *NullableRemoteStoreRestoreResponseContent) Set(val *RemoteStoreRestoreResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoteStoreRestoreResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoteStoreRestoreResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoteStoreRestoreResponseContent(val *RemoteStoreRestoreResponseContent) *NullableRemoteStoreRestoreResponseContent {
	return &NullableRemoteStoreRestoreResponseContent{value: val, isSet: true}
}

func (v NullableRemoteStoreRestoreResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoteStoreRestoreResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


