/*
OpenSearch

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-11-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IndicesPutMappingPostResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndicesPutMappingPostResponseContent{}

// IndicesPutMappingPostResponseContent struct for IndicesPutMappingPostResponseContent
type IndicesPutMappingPostResponseContent struct {
	Acknowledged *bool `json:"acknowledged,omitempty"`
}

// NewIndicesPutMappingPostResponseContent instantiates a new IndicesPutMappingPostResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndicesPutMappingPostResponseContent() *IndicesPutMappingPostResponseContent {
	this := IndicesPutMappingPostResponseContent{}
	return &this
}

// NewIndicesPutMappingPostResponseContentWithDefaults instantiates a new IndicesPutMappingPostResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndicesPutMappingPostResponseContentWithDefaults() *IndicesPutMappingPostResponseContent {
	this := IndicesPutMappingPostResponseContent{}
	return &this
}

// GetAcknowledged returns the Acknowledged field value if set, zero value otherwise.
func (o *IndicesPutMappingPostResponseContent) GetAcknowledged() bool {
	if o == nil || IsNil(o.Acknowledged) {
		var ret bool
		return ret
	}
	return *o.Acknowledged
}

// GetAcknowledgedOk returns a tuple with the Acknowledged field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndicesPutMappingPostResponseContent) GetAcknowledgedOk() (*bool, bool) {
	if o == nil || IsNil(o.Acknowledged) {
		return nil, false
	}
	return o.Acknowledged, true
}

// HasAcknowledged returns a boolean if a field has been set.
func (o *IndicesPutMappingPostResponseContent) HasAcknowledged() bool {
	if o != nil && !IsNil(o.Acknowledged) {
		return true
	}

	return false
}

// SetAcknowledged gets a reference to the given bool and assigns it to the Acknowledged field.
func (o *IndicesPutMappingPostResponseContent) SetAcknowledged(v bool) {
	o.Acknowledged = &v
}

func (o IndicesPutMappingPostResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndicesPutMappingPostResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Acknowledged) {
		toSerialize["acknowledged"] = o.Acknowledged
	}
	return toSerialize, nil
}

type NullableIndicesPutMappingPostResponseContent struct {
	value *IndicesPutMappingPostResponseContent
	isSet bool
}

func (v NullableIndicesPutMappingPostResponseContent) Get() *IndicesPutMappingPostResponseContent {
	return v.value
}

func (v *NullableIndicesPutMappingPostResponseContent) Set(val *IndicesPutMappingPostResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableIndicesPutMappingPostResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableIndicesPutMappingPostResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndicesPutMappingPostResponseContent(val *IndicesPutMappingPostResponseContent) *NullableIndicesPutMappingPostResponseContent {
	return &NullableIndicesPutMappingPostResponseContent{value: val, isSet: true}
}

func (v NullableIndicesPutMappingPostResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndicesPutMappingPostResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


