/*
OpenSearch

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-11-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IndicesGetDataStreamResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndicesGetDataStreamResponseContent{}

// IndicesGetDataStreamResponseContent struct for IndicesGetDataStreamResponseContent
type IndicesGetDataStreamResponseContent struct {
	DataStreams []DataStream `json:"data_streams,omitempty"`
}

// NewIndicesGetDataStreamResponseContent instantiates a new IndicesGetDataStreamResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndicesGetDataStreamResponseContent() *IndicesGetDataStreamResponseContent {
	this := IndicesGetDataStreamResponseContent{}
	return &this
}

// NewIndicesGetDataStreamResponseContentWithDefaults instantiates a new IndicesGetDataStreamResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndicesGetDataStreamResponseContentWithDefaults() *IndicesGetDataStreamResponseContent {
	this := IndicesGetDataStreamResponseContent{}
	return &this
}

// GetDataStreams returns the DataStreams field value if set, zero value otherwise.
func (o *IndicesGetDataStreamResponseContent) GetDataStreams() []DataStream {
	if o == nil || IsNil(o.DataStreams) {
		var ret []DataStream
		return ret
	}
	return o.DataStreams
}

// GetDataStreamsOk returns a tuple with the DataStreams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndicesGetDataStreamResponseContent) GetDataStreamsOk() ([]DataStream, bool) {
	if o == nil || IsNil(o.DataStreams) {
		return nil, false
	}
	return o.DataStreams, true
}

// HasDataStreams returns a boolean if a field has been set.
func (o *IndicesGetDataStreamResponseContent) HasDataStreams() bool {
	if o != nil && !IsNil(o.DataStreams) {
		return true
	}

	return false
}

// SetDataStreams gets a reference to the given []DataStream and assigns it to the DataStreams field.
func (o *IndicesGetDataStreamResponseContent) SetDataStreams(v []DataStream) {
	o.DataStreams = v
}

func (o IndicesGetDataStreamResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndicesGetDataStreamResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DataStreams) {
		toSerialize["data_streams"] = o.DataStreams
	}
	return toSerialize, nil
}

type NullableIndicesGetDataStreamResponseContent struct {
	value *IndicesGetDataStreamResponseContent
	isSet bool
}

func (v NullableIndicesGetDataStreamResponseContent) Get() *IndicesGetDataStreamResponseContent {
	return v.value
}

func (v *NullableIndicesGetDataStreamResponseContent) Set(val *IndicesGetDataStreamResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableIndicesGetDataStreamResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableIndicesGetDataStreamResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndicesGetDataStreamResponseContent(val *IndicesGetDataStreamResponseContent) *NullableIndicesGetDataStreamResponseContent {
	return &NullableIndicesGetDataStreamResponseContent{value: val, isSet: true}
}

func (v NullableIndicesGetDataStreamResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndicesGetDataStreamResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


