/*
OpenSearch

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-11-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opensearch

import (
	"encoding/json"
)

// checks if the DeleteAllPitsResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteAllPitsResponseContent{}

// DeleteAllPitsResponseContent struct for DeleteAllPitsResponseContent
type DeleteAllPitsResponseContent struct {
	Pits []PitsDetailsDeleteAll `json:"pits,omitempty"`
}

// NewDeleteAllPitsResponseContent instantiates a new DeleteAllPitsResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteAllPitsResponseContent() *DeleteAllPitsResponseContent {
	this := DeleteAllPitsResponseContent{}
	return &this
}

// NewDeleteAllPitsResponseContentWithDefaults instantiates a new DeleteAllPitsResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteAllPitsResponseContentWithDefaults() *DeleteAllPitsResponseContent {
	this := DeleteAllPitsResponseContent{}
	return &this
}

// GetPits returns the Pits field value if set, zero value otherwise.
func (o *DeleteAllPitsResponseContent) GetPits() []PitsDetailsDeleteAll {
	if o == nil || IsNil(o.Pits) {
		var ret []PitsDetailsDeleteAll
		return ret
	}
	return o.Pits
}

// GetPitsOk returns a tuple with the Pits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteAllPitsResponseContent) GetPitsOk() ([]PitsDetailsDeleteAll, bool) {
	if o == nil || IsNil(o.Pits) {
		return nil, false
	}
	return o.Pits, true
}

// HasPits returns a boolean if a field has been set.
func (o *DeleteAllPitsResponseContent) HasPits() bool {
	if o != nil && !IsNil(o.Pits) {
		return true
	}

	return false
}

// SetPits gets a reference to the given []PitsDetailsDeleteAll and assigns it to the Pits field.
func (o *DeleteAllPitsResponseContent) SetPits(v []PitsDetailsDeleteAll) {
	o.Pits = v
}

func (o DeleteAllPitsResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteAllPitsResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pits) {
		toSerialize["pits"] = o.Pits
	}
	return toSerialize, nil
}

type NullableDeleteAllPitsResponseContent struct {
	value *DeleteAllPitsResponseContent
	isSet bool
}

func (v NullableDeleteAllPitsResponseContent) Get() *DeleteAllPitsResponseContent {
	return v.value
}

func (v *NullableDeleteAllPitsResponseContent) Set(val *DeleteAllPitsResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteAllPitsResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteAllPitsResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteAllPitsResponseContent(val *DeleteAllPitsResponseContent) *NullableDeleteAllPitsResponseContent {
	return &NullableDeleteAllPitsResponseContent{value: val, isSet: true}
}

func (v NullableDeleteAllPitsResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteAllPitsResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


