/*
OpenSearch

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-11-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateActionGroupResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateActionGroupResponseContent{}

// CreateActionGroupResponseContent struct for CreateActionGroupResponseContent
type CreateActionGroupResponseContent struct {
	// Security Operation Status
	Status *string `json:"status,omitempty"`
	// Security Operation Message
	Message *string `json:"message,omitempty"`
}

// NewCreateActionGroupResponseContent instantiates a new CreateActionGroupResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateActionGroupResponseContent() *CreateActionGroupResponseContent {
	this := CreateActionGroupResponseContent{}
	return &this
}

// NewCreateActionGroupResponseContentWithDefaults instantiates a new CreateActionGroupResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateActionGroupResponseContentWithDefaults() *CreateActionGroupResponseContent {
	this := CreateActionGroupResponseContent{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateActionGroupResponseContent) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateActionGroupResponseContent) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateActionGroupResponseContent) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CreateActionGroupResponseContent) SetStatus(v string) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateActionGroupResponseContent) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateActionGroupResponseContent) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateActionGroupResponseContent) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateActionGroupResponseContent) SetMessage(v string) {
	o.Message = &v
}

func (o CreateActionGroupResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateActionGroupResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableCreateActionGroupResponseContent struct {
	value *CreateActionGroupResponseContent
	isSet bool
}

func (v NullableCreateActionGroupResponseContent) Get() *CreateActionGroupResponseContent {
	return v.value
}

func (v *NullableCreateActionGroupResponseContent) Set(val *CreateActionGroupResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateActionGroupResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateActionGroupResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateActionGroupResponseContent(val *CreateActionGroupResponseContent) *NullableCreateActionGroupResponseContent {
	return &NullableCreateActionGroupResponseContent{value: val, isSet: true}
}

func (v NullableCreateActionGroupResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateActionGroupResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


