/*
OpenSearch

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2021-11-23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opensearch

import (
	"encoding/json"
)

// checks if the DataStreamTimestampField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataStreamTimestampField{}

// DataStreamTimestampField struct for DataStreamTimestampField
type DataStreamTimestampField struct {
	Name *string `json:"name,omitempty"`
}

// NewDataStreamTimestampField instantiates a new DataStreamTimestampField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataStreamTimestampField() *DataStreamTimestampField {
	this := DataStreamTimestampField{}
	return &this
}

// NewDataStreamTimestampFieldWithDefaults instantiates a new DataStreamTimestampField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataStreamTimestampFieldWithDefaults() *DataStreamTimestampField {
	this := DataStreamTimestampField{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DataStreamTimestampField) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataStreamTimestampField) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DataStreamTimestampField) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DataStreamTimestampField) SetName(v string) {
	o.Name = &v
}

func (o DataStreamTimestampField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataStreamTimestampField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableDataStreamTimestampField struct {
	value *DataStreamTimestampField
	isSet bool
}

func (v NullableDataStreamTimestampField) Get() *DataStreamTimestampField {
	return v.value
}

func (v *NullableDataStreamTimestampField) Set(val *DataStreamTimestampField) {
	v.value = val
	v.isSet = true
}

func (v NullableDataStreamTimestampField) IsSet() bool {
	return v.isSet
}

func (v *NullableDataStreamTimestampField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataStreamTimestampField(val *DataStreamTimestampField) *NullableDataStreamTimestampField {
	return &NullableDataStreamTimestampField{value: val, isSet: true}
}

func (v NullableDataStreamTimestampField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataStreamTimestampField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


